feat: 🎸 Add basic header
fktrelleborg/fk-trelleborg pull request #21
Opened 2024-09-07 18:59 UTC by SiriusDreamz

Added a basic header (to be improved upon), also acting as an example on how to work with styled components and export thinking. Improvements during a hackaton can be functionality, styling, etc.

Also:

- Remove package-lock.json
- Add package-lock.json to .gitignore as a failsafe
- Rewrote .yml script files to use yarn instead of npm to not use both yarn and npm in our project.
- Add exported color variables for CSS.

Now, only yarn-lock is used.

✅ Closes: #18
✅ Closes: #20

2024-09-09 11:06 UTC, fktrelleborg requested changes

2024-09-09 11:06 UTC, fktrelleborg commented on src/Components/Header/Header.jsx
> +          </HeaderLi>
Ta bort denna

2024-09-09 13:43 UTC, SiriusDreamz commented on src/Components/Header/Header.jsx
> +          </HeaderLi>
Fixat!

2024-09-10 07:28 UTC, fktrelleborg approved these changes

2024-09-10 08:27 UTC, merged